#!/usr/bin/env python3
"""Local, auditable project memory for Riyadh Natural-20.

Commands:
  ingest  Compile checkpoint logs and GitHub Actions into Markdown.
  query   Rank and cite relevant vault notes with lexical search.
  audit   Check wikilinks, required evidence, and score-scope claims.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path


VAULT = Path(__file__).resolve().parent
REQUIRED = (
  "Home.md",
  "Decisions/Scale-Gate.md",
  "Evidence/Verified-Scores.md",
  "Submission/Checklist.md",
  "Submission/Controller-Design.md",
  "Sources/Comma-Official.md",
)


def utc_now() -> str:
  return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def load_records(repo_root: Path):
  patterns = (
    "checkpoints/autopilot-progress.jsonl",
    "checkpoints/pilot/progress.jsonl",
    "checkpoints/pilot/refined-progress.jsonl",
    "checkpoints/**/progress*.jsonl",
  )
  paths = []
  for pattern in patterns:
    paths.extend(repo_root.glob(pattern))
  unique = sorted(set(p.resolve() for p in paths if p.is_file()))
  records = []
  for path in unique:
    with path.open(encoding="utf-8") as stream:
      for line_no, line in enumerate(stream, 1):
        if not line.strip():
          continue
        record = json.loads(line)
        if record.get("status") != "completed" or "stock_cost" not in record:
          continue
        record = dict(record)
        record["_source"] = str(path.relative_to(repo_root))
        record["_line"] = line_no
        records.append(record)
  return records


def fetch_runs(repo: str, limit: int = 30):
  url = f"https://api.github.com/repos/{repo}/actions/runs?per_page={limit}"
  request = urllib.request.Request(
    url,
    headers={"Accept": "application/vnd.github+json", "User-Agent": "natural20-brain"},
  )
  with urllib.request.urlopen(request, timeout=30) as response:
    payload = json.load(response)
  return payload.get("workflow_runs", [])


def latest_by_segment(records):
  latest = {}
  for record in records:
    latest[str(record["segment"]).zfill(5)] = record
  return latest


def write_generated_results(records):
  latest = latest_by_segment(records)
  rows = []
  for segment, record in sorted(latest.items()):
    score = float(record["stock_cost"])
    previous = record.get("previous_stock_cost")
    previous_text = f"{float(previous):.6f}" if previous is not None else "—"
    parity = float(record.get("parity_delta", 0.0))
    rows.append(
      f"| {segment} | {score:.6f} | {previous_text} | "
      f"{record.get('method', 'unknown')} | {parity:.3g} | "
      f"`{record['_source']}:{record['_line']}` |"
    )
  costs = [float(r["stock_cost"]) for r in latest.values()]
  mean = sum(costs) / len(costs) if costs else float("nan")
  under = sum(c < 20 for c in costs)
  content = f"""---
type: generated-evidence
scope: per-segment-checkpoints
generated_at: {utc_now()}
verified_segments: {len(costs)}
---

# Auto Results

> [!warning] Evaluation scope
> These are deterministic stock-simulator checkpoint scores for individual segments.
> They are **not** a comma leaderboard score. Only the official 5000-segment
> `report.html` may be labeled as the submission score.

| Segment | Latest stock cost | Previous | Method | Parity delta | Evidence |
|---|---:|---:|---|---:|---|
{chr(10).join(rows)}

## Snapshot

- Verified checkpoint segments: **{len(costs)}**
- Mean over available checkpoints: **{mean:.6f}**
- Checkpoints below 20: **{under}/{len(costs)}**
- Official 5000-segment score: **not available**

See [[Evidence/Verified-Scores]] and [[Decisions/Scale-Gate]].
"""
  path = VAULT / "Experiments" / "Auto-Results.md"
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(content, encoding="utf-8")
  return latest, mean, under


def write_runs(runs):
  rows = []
  for run in runs:
    rows.append(
      "| [{name} #{number}]({url}) | {status} | {conclusion} | {created} | `{sha}` |".format(
        name=run.get("name", "workflow"), number=run.get("run_number", "?"),
        url=run.get("html_url", ""), status=run.get("status", "unknown"),
        conclusion=run.get("conclusion") or "—", created=run.get("created_at", "—"),
        sha=str(run.get("head_sha", ""))[:8],
      )
    )
  content = f"""---
type: generated-evidence
generated_at: {utc_now()}
---

# GitHub Runs

| Run | Status | Conclusion | Created (UTC) | Commit |
|---|---|---|---|---|
{chr(10).join(rows)}

This page is generated by `python knowledge/brain.py ingest`.
"""
  path = VAULT / "Evidence" / "GitHub-Runs.md"
  path.parent.mkdir(parents=True, exist_ok=True)
  path.write_text(content, encoding="utf-8")


def update_home(latest, mean, under):
  score0 = latest.get("00000", {}).get("stock_cost")
  score0_text = f"{float(score0):.6f}" if score0 is not None else "not available"
  content = f"""---
type: dashboard
project: Riyadh Natural-20
updated_at: {utc_now()}
official_submission_score: null
---

# Riyadh Natural-20 / الرياض — الهدف الطبيعي 20

> [!info] Current truth
> The best verified checkpoint for segment `00000` is **{score0_text}**.
> The mean across the **{len(latest)} available per-segment checkpoints** is
> **{mean:.6f}**, with **{under}** below 20. This is not a leaderboard result.

## Navigation

- [[Experiments/Auto-Results|Generated experiment results]]
- [[Experiments/Segment-00000|Segment 00000 history]]
- [[Experiments/Pilot-00001-00010|Ten-segment pilot]]
- [[Experiments/General-Controller-V1|General controller V1]]
- [[Experiments/General-Controller-V2-V4|General controller rejected iterations]]
- [[Decisions/Scale-Gate|Scale decision]]
- [[Decisions/General-Controller-Track|General controller decision]]
- [[Evidence/Verified-Scores|Verified scores and evidence rules]]
- [[Evidence/GitHub-Runs|GitHub execution history]]
- [[Submission/Controller-Design|Controller design]]
- [[Submission/Checklist|Official submission checklist]]
- [[Project-Discovery-Answers|Repository-backed discovery answers]]
- [[Sources/Comma-Official|Official comma sources]]
- [[Templates/Experiment|New experiment template]]

## Three commands

```bash
python knowledge/brain.py ingest --repo-root . --github-repo HadiRx/wasfa-project
python knowledge/brain.py query "why did we not scale to 5000"
python knowledge/brain.py audit --strict
```
"""
  (VAULT / "Home.md").write_text(content, encoding="utf-8")


def ingest(args):
  repo_root = Path(args.repo_root).resolve()
  records = load_records(repo_root)
  latest, mean, under = write_generated_results(records)
  if args.github_repo:
    try:
      write_runs(fetch_runs(args.github_repo))
    except Exception as exc:
      print(f"WARNING: GitHub run ingestion skipped: {type(exc).__name__}: {exc}")
  update_home(latest, mean, under)
  print(f"INGEST_OK records={len(records)} latest_segments={len(latest)} mean={mean:.6f}")


def markdown_files():
  return sorted(p for p in VAULT.rglob("*.md") if ".obsidian" not in p.parts)


def tokens(text):
  return [t.casefold() for t in re.findall(r"[^\W_]{2,}", text, flags=re.UNICODE)]


def query(args):
  wanted = Counter(tokens(args.question))
  ranked = []
  for path in markdown_files():
    text = path.read_text(encoding="utf-8")
    counts = Counter(tokens(text))
    score = sum((1 + wanted[word]) * min(counts[word], 8) for word in wanted)
    if score:
      lower = text.casefold()
      positions = [lower.find(word) for word in wanted if lower.find(word) >= 0]
      pos = min(positions) if positions else 0
      start, end = max(0, pos - 180), min(len(text), pos + 420)
      snippet = re.sub(r"\s+", " ", text[start:end]).strip()
      ranked.append((score, path, snippet))
  ranked.sort(key=lambda item: (-item[0], str(item[1])))
  if not ranked:
    raise SystemExit("No matching notes.")
  for score, path, snippet in ranked[:args.limit]:
    rel = path.relative_to(VAULT).with_suffix("")
    print(f"[[{rel.as_posix()}]] score={score}\n{snippet}\n")


def note_targets():
  targets = set()
  for path in markdown_files():
    rel = path.relative_to(VAULT).with_suffix("").as_posix()
    targets.add(rel.casefold())
    targets.add(path.stem.casefold())
  return targets


def audit(args):
  errors, warnings = [], []
  for required in REQUIRED:
    if not (VAULT / required).exists():
      errors.append(f"missing required note: {required}")

  targets = note_targets()
  inbound = defaultdict(int)
  link_re = re.compile(r"\[\[([^\]]+)\]\]")
  for path in markdown_files():
    text = path.read_text(encoding="utf-8")
    for raw in link_re.findall(text):
      target = raw.split("|", 1)[0].split("#", 1)[0].strip()
      key = target.casefold()
      if key not in targets and Path(target).name.casefold() not in targets:
        errors.append(f"broken wikilink in {path.relative_to(VAULT)}: [[{raw}]]")
      else:
        inbound[key] += 1
    if re.search(r"official_submission_score:\s*(?!null\b)\S+", text):
      errors.append(f"unverified official score claim in {path.relative_to(VAULT)}")

  for path in markdown_files():
    if path.name in {"Home.md", "AGENTS.md"}:
      continue
    rel = path.relative_to(VAULT).with_suffix("").as_posix().casefold()
    if inbound[rel] == 0 and inbound[path.stem.casefold()] == 0:
      warnings.append(f"orphan note: {path.relative_to(VAULT)}")

  for item in errors:
    print(f"ERROR {item}")
  for item in warnings:
    print(f"WARNING {item}")
  print(f"AUDIT_DONE errors={len(errors)} warnings={len(warnings)} notes={len(markdown_files())}")
  if errors or (args.strict and warnings):
    raise SystemExit(1)


def main():
  parser = argparse.ArgumentParser()
  sub = parser.add_subparsers(dest="command", required=True)
  p_ingest = sub.add_parser("ingest")
  p_ingest.add_argument("--repo-root", default=VAULT.parent)
  p_ingest.add_argument("--github-repo", default="")
  p_ingest.set_defaults(func=ingest)
  p_query = sub.add_parser("query")
  p_query.add_argument("question")
  p_query.add_argument("--limit", type=int, default=5)
  p_query.set_defaults(func=query)
  p_audit = sub.add_parser("audit")
  p_audit.add_argument("--strict", action="store_true")
  p_audit.set_defaults(func=audit)
  args = parser.parse_args()
  args.func(args)


if __name__ == "__main__":
  main()
