"""Build a reproducible comma Controls Challenge v2 submission directory."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil


def sha256(path: Path) -> str:
  h = hashlib.sha256()
  with path.open("rb") as f:
    for chunk in iter(lambda: f.read(1024 * 1024), b""):
      h.update(chunk)
  return h.hexdigest()


def main(a):
  out = Path(a.output)
  if out.exists():
    shutil.rmtree(out)
  (out / "controllers").mkdir(parents=True)
  (out / "models").mkdir(parents=True)
  (out / "evidence").mkdir(parents=True)

  shutil.copy2(a.controller, out / "controllers" / "riyadh_v13c.py")
  shutil.copy2(a.policy_model, out / "models" / "riyadh_general_policy.npz")
  shutil.copy2(a.inverse_model, out / "models" / "riyadh_inverse_linear.npz")
  shutil.copy2(a.report_html, out / "report.html")
  shutil.copy2(a.verification_1000, out / "evidence" / "verification_1000.json")
  shutil.copy2(a.verification_5000, out / "evidence" / "verification_5000.json")
  shutil.copy2(a.v13c_summary, out / "evidence" / "v13c_refinement_summary.json")

  readme = f"""# Riyadh Natural-20 — V13-C Submission

Author: Hadi Alanazi
Email: hadi-alenzi@hotmail.com

This package contains the frozen V13-C hard-guard controller for comma Controls Challenge v2.

## Official evaluation command

```bash
python eval.py --model_path ./models/tinyphysics.onnx --data_path ./data --num_segs 5000 --test_controller riyadh_v13c --baseline_controller pid
```

Copy `controllers/riyadh_v13c.py` into the official repository's `controllers/` directory and copy the two `.npz` files into its `models/` directory before running the command.

## Contents

- `report.html`: official 5,000-segment report generated by comma's `eval.py`.
- `controllers/riyadh_v13c.py`: controller source.
- `models/riyadh_general_policy.npz`: frozen V13-C policy and controller parameters.
- `models/riyadh_inverse_linear.npz`: frozen inverse model used by the controller.
- `evidence/verification_1000.json`: independent 1,000-segment paired verification.
- `evidence/verification_5000.json`: independent 5,000-segment paired verification.
- `evidence/v13c_refinement_summary.json`: development and holdout history.
- `MANIFEST.json` and `SHA256SUMS.txt`: provenance and integrity checks.

## Method summary

V13-C starts from the accepted V13-A controller and uses low-dimensional CMA-ES refinement against the official TinyPhysics closed-loop cost. A fixed hard-case guard set is evaluated during search to penalize regressions in known failure modes. Candidate acceptance requires improvements in mean, median, and worst cost on fresh development data, followed by a fresh holdout gate.

The final frozen candidate was subsequently verified on 1,000 and 5,000 additional paired segments. No simulator patching, hidden-data access, route-specific branching, or random runtime behavior is used by the submitted controller.
"""
  (out / "README.md").write_text(readme, encoding="utf-8")

  files = sorted(p for p in out.rglob("*") if p.is_file())
  checksums = {str(p.relative_to(out)): sha256(p) for p in files}
  manifest = {
    "name": "Riyadh Natural-20 V13-C Hard Guard Controller",
    "author": "Hadi Alanazi",
    "email": "hadi-alenzi@hotmail.com",
    "challenge": "comma Controls Challenge v2",
    "source_commit": a.commit,
    "official_controls_challenge_commit": a.official_commit,
    "controller_name": "riyadh_v13c",
    "evaluation_segments": 5000,
    "deterministic": True,
    "files": checksums,
  }
  (out / "MANIFEST.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")

  files = sorted(p for p in out.rglob("*") if p.is_file() and p.name != "SHA256SUMS.txt")
  lines = [f"{sha256(p)}  {p.relative_to(out)}" for p in files]
  (out / "SHA256SUMS.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
  print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
  p = argparse.ArgumentParser()
  p.add_argument("--controller", required=True)
  p.add_argument("--policy-model", required=True)
  p.add_argument("--inverse-model", required=True)
  p.add_argument("--report-html", required=True)
  p.add_argument("--verification-1000", required=True)
  p.add_argument("--verification-5000", required=True)
  p.add_argument("--v13c-summary", required=True)
  p.add_argument("--commit", required=True)
  p.add_argument("--official-commit", required=True)
  p.add_argument("--output", required=True)
  main(p.parse_args())
